//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.ACCOUNT_AUTHORIZED = new HashSet<ACCOUNT_AUTHORIZED>();
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.PATIENT_QUEUE = new HashSet<PATIENT_QUEUE>();
            this.TREATMENT_PLAN = new HashSet<TREATMENT_PLAN>();
        }
    
        public int DOCTOR_ID { get; set; }
        public string NAME { get; set; }
        public string SPECIALIST { get; set; }
        public string ROOM { get; set; }
        public Nullable<bool> READY { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_AUTHORIZED> ACCOUNT_AUTHORIZED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_QUEUE> PATIENT_QUEUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT_PLAN> TREATMENT_PLAN { get; set; }
    }
}
