//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTTQEntities : DbContext
    {
        public LTTQEntities()
            : base("name=LTTQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT_AUTHORIZED> ACCOUNT_AUTHORIZED { get; set; }
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<DIRECTOR> DIRECTORs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<MEDICINE> MEDICINEs { get; set; }
        public virtual DbSet<PATIENT> PATIENTs { get; set; }
        public virtual DbSet<PATIENT_QUEUE> PATIENT_QUEUE { get; set; }
        public virtual DbSet<PATIENT_SICK_BED> PATIENT_SICK_BED { get; set; }
        public virtual DbSet<RECEPTIONIST> RECEPTIONISTs { get; set; }
        public virtual DbSet<RELATIONSHIP> RELATIONSHIPs { get; set; }
        public virtual DbSet<SICK_BED> SICK_BED { get; set; }
        public virtual DbSet<TREATMENT_PLAN> TREATMENT_PLAN { get; set; }
        public virtual DbSet<TREATMENT_PLAN_MEDICINE> TREATMENT_PLAN_MEDICINE { get; set; }
        public virtual DbSet<WAREHOUSE_STAFF> WAREHOUSE_STAFF { get; set; }
    }
}
