//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string ID { get; set; }
    }
}
