//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_SICK_BED
    {
        public int SICK_BED_ID { get; set; }
        public int PATIENT_ID { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
        public virtual SICK_BED SICK_BED { get; set; }
    }
}
