//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.PATIENT_QUEUE = new HashSet<PATIENT_QUEUE>();
            this.PATIENT_SICK_BED = new HashSet<PATIENT_SICK_BED>();
            this.RELATIONSHIPs = new HashSet<RELATIONSHIP>();
            this.TREATMENT_PLAN = new HashSet<TREATMENT_PLAN>();
        }
    
        public int PATIENT_ID { get; set; }
        public string NAME { get; set; }
        public string BORN_PLACE { get; set; }
        public Nullable<bool> SEX { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> INSURANCE_ID { get; set; }
        public Nullable<int> SICK_BED_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_QUEUE> PATIENT_QUEUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_SICK_BED> PATIENT_SICK_BED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELATIONSHIP> RELATIONSHIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT_PLAN> TREATMENT_PLAN { get; set; }
    }
}
