//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SICK_BED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SICK_BED()
        {
            this.PATIENT_SICK_BED = new HashSet<PATIENT_SICK_BED>();
        }
    
        public int SICK_BED_ID { get; set; }
        public string ROOM { get; set; }
        public Nullable<bool> IS_AVAILABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_SICK_BED> PATIENT_SICK_BED { get; set; }
    }
}
