//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENT_PLAN_MEDICINE
    {
        public int MEDICINE_ID { get; set; }
        public int TREATMENT_PLAN_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual MEDICINE MEDICINE { get; set; }
        public virtual TREATMENT_PLAN TREATMENT_PLAN { get; set; }
    }
}
