//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENT_PLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TREATMENT_PLAN()
        {
            this.TREATMENT_PLAN_MEDICINE = new HashSet<TREATMENT_PLAN_MEDICINE>();
        }
    
        public int TREATMENT_PLAN_ID { get; set; }
        public Nullable<System.DateTime> TREATMENT_PLAN_DATE { get; set; }
        public string MEDICAL_INSTRUCTION { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public Nullable<int> PATIENT_ID { get; set; }
        public string SYMPTOM { get; set; }
        public string HEALTH_STATUS { get; set; }
        public Nullable<bool> IS_PAID { get; set; }
        public Nullable<int> PRICE { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT_PLAN_MEDICINE> TREATMENT_PLAN_MEDICINE { get; set; }
    }
}
