//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_v2.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_STAFF
    {
        public int WAREHOUSE_STAFF_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
